MontanaFlossCo/Flint

- FlintCore/Actions/ActionContext.swift
- FlintCore/Actions/ActionRequest.swift
- FlintCore/Actions/NoPresenter.swift
- FlintCore/Actions/StaticActionBinding.swift
- FlintCore/Activities/ActivityActionDispatchObserver.swift
- FlintCore/Activities/HandleActivityAction.swift
- FlintCore/Activities/PublishCurrentActionActivityAction.swift
- FlintCore/Conditional Features/ConditionalActionRequest.swift
- FlintCore/Core/ActionSession.swift
- FlintCore/Core/ActionStackEntry.swift
- FlintCore/Focus/FocusFeature.swift
- FlintCore/Routes/PerformIncomingURLAction.swift
- FlintCore/Timeline/Timeline.swift
- FlintCoreTests/DebugReportingTests.swift
- FlintUI/Features/FocusLogDataAccessFeature.swift
- FlintUI/Features/TimelineDataAccessFeature.swift
- FlintUISandbox/AppDelegate.swift
- FlintUISandbox/ViewController.swift
This greatly improves the ergonomics of performing actions that either need no input, no presenter or need neither.
It also means actions no longer need to test for possibly nil input, because we couldn't specify optional associated types due to Swift limitations.
Fixes #49
> New improved NoInput/NoPresenter handling, cleaner `perform` impls

- FlintCore.xcodeproj/project.pbxproj
- FlintCore.xcodeproj/xcshareddata/xcschemes/FlintCore-iOS.xcscheme
- FlintCore/Activities/ActivitiesFeature.swift
- FlintCore/Conditional Features/AvailabilityChecker.swift
- FlintCore/Conditional Features/ConditionalFeatureDefinition.swift
- FlintCore/Conditional Features/DefaultAvailabilityChecker.swift
- FlintCore/Conditional Features/FeatureAvailability.swift
- FlintCore/Conditional Features/PurchaseTracker.swift
- FlintCore/Conditional Features/PurchaseTrackerObserver.swift
- FlintCore/Focus/FocusFeature.swift
- FlintCore/Purchases/PurchaseRequirement.swift
- FlintCore/Purchases/StoreKitPurchaseTracker.swift
- FlintCore/Routes/RoutesFeature.swift
- FlintCore/Timeline/TimelineFeature.swift
- FlintCore/Utils/ObserverSet.swift
- FlintCore/Utils/TimeOrderedResultsController.swift
- FlintCoreTests/DefaultAvailabilityCheckerTests.swift
- FlintCoreTests/FlintCoreTests.swift
- FlintCoreTests/Mocks and Helpers/MockPurchaseValidator.swift
- FlintCoreTests/Mocks and Helpers/MockUserToggles.swift
- FlintUI/Features/FocusLogDataAccessFeature.swift
- FlintUI/Features/LogBrowserFeature.swift
- FlintUI/Features/TimelineBrowserFeature.swift
- FlintUI/Features/TimelineDataAccessFeature.swift
In order to tackle threadsafety, asynchronous changes to availability (e.g. purchase verifications) and support hierarchical feature availability (all ancestors must be available for a grandchild to be available too).
Work involved:
* the name of "runtimeEvaluated" to "custom", as it is less confusing
* the return of the availability checker and purchase validators all have too be `Bool?` so we don't lose information about indeterminate states
* added observing to the purchase tracker 
* the addition of hierarchical testing of availability
* unit tests!
> Rework availability checking and purchase checking APIs

- FlintCore/Core/Flint.swift
This doesn't make much sense to me, as we compiled fine on 9.3 and ClassKit was available but... ho hum. Xcode 9.4 fails to compile without this added.
> Xcode 9.4 chokes on missing “#if available”

- FlintCore.xcodeproj/project.pbxproj
- FlintCore/Conditional Features/ConditionalFeature.swift
- FlintCore/Constraints/Permissions/CameraPermissionAdapter.swift
- FlintCore/Constraints/Permissions/ContactsPermissionAdapter.swift
- FlintCore/Constraints/Permissions/DefaultAuthorisationController.swift
- FlintCore/Constraints/Permissions/DefaultPermissionChecker.swift
- FlintCore/Constraints/Permissions/LocationPermissionAdapter.swift
- FlintCore/Constraints/Permissions/PhotosPermissionAdapter.swift
- FlintCore/Constraints/Permissions/SystemPermissionAdapter.swift
- FlintCore/Constraints/Permissions/SystemPermissionConstraint.swift
- FlintUISandbox/AppDelegate.swift
- FlintUISandbox/Info.plist
Turned out the build-time and runtime platform checks were onerous because you had to check them before creating the permission adapter. I've refactored that so permission adapters can encapsulate all of that themselves and simply indicate whether or not they are valid for the current platform.
> Add support for Contacts permission and clean up some stuff

- Flint.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- FlintCore/Conditional Features/ConditionalFeature.swift
- FlintCore/Constraints/Permissions/DefaultAuthorisationController.swift
- FlintCore/Constraints/Permissions/DefaultPermissionChecker.swift
- FlintCore/Constraints/Permissions/LocationPermissionAdapter.swift
- FlintCore/Core/ActionSession.swift
- FlintCore/Core/Flint.swift
- FlintCore/Features/FeatureMetadata.swift
- FlintUISandbox/AppDelegate.swift
Undeclared actions mean we don't have metadata for the actions, which defeats the feature browser and conditional availability etc.
Also some fly-by fixes to location permissions and the authorisation controller because bad things were happening. Core Location tell us auth status changed simply by us asking for it (at least in the simulator) so we protect against this false information now as it could screw up the state of the auth controller.
> Catch undeclared actions and help the use solve the problem

- FlintCore/Activities/ActivityBuilder.swift
Siri ProActive wouldn’t work because there's no userInfo it knows it needs to persist/consider
> Fix requiredUserInfoKeys not including auto url

- FlintCore/Core/Flint.swift
- FlintCoreTests/FlintCoreTests.swift
It seems that there is real-world use for conditional features that are also parents of others, and this avoids having to create an artificial non-conditional group in between.
Now feature groups will be registered just like normal features (conditional or otherwise), actions prepared and urls mapped etc.
> Feature groups that are also conditional/have actions are useful. Support them!

- FlintCore.xcodeproj/project.pbxproj
- FlintCore/Constraints/Permissions/CameraPermissionAdapter.swift
- FlintCore/Constraints/Permissions/ContactsPermissionAdapter.swift
- FlintCore/Constraints/Permissions/DefaultPermissionChecker.swift
- FlintCore/Constraints/Permissions/EventKitPermissionAdapter.swift
- FlintCore/Constraints/Permissions/LocationPermissionAdapter.swift
- FlintCore/Constraints/Permissions/MotionPermissionAdapter.swift
- FlintCore/Constraints/Permissions/PhotosPermissionAdapter.swift
- FlintCore/Constraints/Permissions/SpeechRecognitionPermissionAdapter.swift
- FlintCore/Constraints/Permissions/SystemPermissionConstraint.swift
- FlintCore/Core/Flint.swift
- FlintCore/Utils/DynamicLibraryBinding.swift
- FlintUI.xcodeproj/project.pbxproj
- FlintUISandbox/AppDelegate.swift
- FlintUISandbox/Info.plist
We had problems with app store processing rejections for missing `NSContactsUsageDescription` and `NSCalendarsUsageDescription` plist keys when these APIs were not being used by the app itself.
This was caused by:
* Implicit dependency on Contacts framework by linking against Intents for the `interaction` property extension on NSUserActivity
* Strongly linking Contacts and EvenKit, via explicit `import Contacts` etc.
* Even without imports and attempted unsafeBitcast to private @objc protocols we were still rejected for using the selectors for requesting access
So we have some dynamic binding code here used for Contacts, EventKit and the small property access for Interns. We still link against frameworks the user may not be using, so we need to improve that in future for performance but …
> Use dynamic linking on permissions APIs where needed

- FlintCore.xcodeproj/project.pbxproj
- FlintCore/Actions/Action.swift
- FlintCore/Actions/ActionContext.swift
- FlintCore/Actions/FlintLoggable.swift
- FlintCore/Actions/NoInput.swift
- FlintCore/Activities/ActivityActionDispatchObserver.swift
- FlintCore/Activities/NSUserActivity+FlintAdditions.swift
- FlintCore/Activities/PublishActivityRequest.swift
- FlintCore/Constraints/Permissions/DefaultPermissionChecker.swift
- FlintCore/Core/ActionSession.swift
- FlintCore/Debug Reporting/InternalJSONFormatting.swift
- FlintCore/Focus/FocusArea.swift
- FlintCore/Routes/RouteParametersCodable.swift
- FlintCore/Timeline/Timeline.swift
- FlintCore/Timeline/TimelineEntry.swift
- FlintUI.xcodeproj/project.pbxproj
- FlintUI/iOS/View Controllers/TimelineEntryViewController.swift
- FlintUISandbox/AppDelegate.swift
- FlintUISandbox/Assets.xcassets/AppIcon.appiconset/Contents.json
- FlintUISandbox/FakeFeatures.swift
- FlintUISandbox/Info.plist
This addresses #139 with different naming.
I think this is pretty solid, in that we now no longer rely on `CustomStringConvertible` and `CustomDebugStringConvertible` which may not be under the developers control (think third party frameworks) and also may be used for other purposes in the app.
The goal for Flint is that we must be able to get a good human readable string for an input for use in logs, and we need structured data for machine-readable post mortem data, so the protocol has this:
```swift
public protocol FlintLoggable {
var loggingDescription: String { get }
var loggingInfo: [String:String]? { get }
```
An extension provides default implementations of these for all types, and specific implementations for standard runtime types.
What is left to establish is how hierarchical …
> Changes InputType to conform to FlintLoggable

- FlintCore/Actions/Action.swift
- FlintCore/Actions/ActionContext.swift
- FlintCore/Actions/StaticActionBinding.swift
- FlintCore/Activities/ActionActivityMappings.swift
- FlintCore/Activities/ActivityActionDispatchObserver.swift
- FlintCore/Activities/HandleActivityAction.swift
- FlintCore/Activities/PerformIncomingActivityAction.swift
- FlintCore/Activities/PublishCurrentActionActivityAction.swift
- FlintCore/Conditional Features/ConditionalActionBinding.swift
- FlintCore/Conditional Features/ConditionalActionRequest.swift
- FlintCore/Core/ActionDispatcher.swift
- FlintCore/Core/ActionSession.swift
- FlintCore/Core/Flint.swift
- FlintCore/Focus/FocusFeature.swift
- FlintCore/Routes/PerformIncomingURLAction.swift
- FlintCore/Routes/PresentationRouter.swift
- FlintCore/Routes/URLMappingsBuilder.swift
- FlintCoreTests/Test Features/DummyFeature.swift
- FlintUI/Features/ActionStackBrowserFeature.swift
- FlintUI/Features/FeatureBrowserFeature.swift
- FlintUI/Features/FocusLogDataAccessFeature.swift
- FlintUI/Features/LogBrowserFeature.swift
- FlintUI/Features/TimelineBrowserFeature.swift
- FlintUI/Features/TimelineDataAccessFeature.swift
- FlintUI/iOS/View Controllers/FocusLogViewController.swift
- FlintUI/iOS/View Controllers/TimelineViewController.swift
- FlintUISandbox/AppDelegate.swift
- FlintUISandbox/FakeFeatures.swift
- FlintUISandbox/ViewController.swift
- README.md
See #143 which states the problem that "with" and "using" do not make it clear which is input and which is presenter. Natural language forms like this appear to work best when there is only one "subject" which naturally disambiguates it.
I renamed related public functions that take input/presenters too, on:
* ActionSession
* StaticActionBinding & ConditionalActionBinding (the primary API touch points)
* PresentationRouter
* Action
The rest is all fix up for internals and FlintUISandbox so they compile and run as before.
> Change arguments on `perform` and related functions to clearer intent

- FlintCore/Routes/URLMappings.swift
The URL mappings are an array of types, not a dictionary, so multiple mappings per action are supported.
> Fix a non-bug by removing false comment

- Cartfile
- FlintCore.xcodeproj/project.pbxproj
- FlintCore.xcodeproj/xcshareddata/xcschemes/FlintCore-iOS-Tests.xcscheme
- FlintCore.xcodeproj/xcshareddata/xcschemes/FlintCore-iOS.xcscheme
- FlintCore/Debug Reporting/DebugReporting.swift
- FlintCore/Utils/Zip/Archive+Writing.swift
- FlintCore/Utils/Zip/Archive.swift
- FlintCore/Utils/Zip/Data+Compression.swift
- FlintCore/Utils/Zip/Data+Serialization.swift
- FlintCore/Utils/Zip/Entry.swift
- FlintCore/Utils/Zip/FileManager+ZIP.swift
The extension-safe API stuff is not set on the original repo, and this removes the need to use carthage at all for Flint itself.
Later we should roll our own / do just what we need with the Apple-provided zip libs but for now this is a quick fix and has the bonus of working on Swift with linux but it's not clear that is a goal.
> Remove external ZIPFoundation dependency by inlining what we need

- FlintCore/Actions/ActionRequest.swift
- FlintCore/Actions/StaticActionBinding.swift
- FlintCore/Activities/ActionActivityMappings.swift
- FlintCore/Activities/ActivityActionDispatchObserver.swift
- FlintCore/Analytics/AnalyticsReporting.swift
- FlintCore/Conditional Features/ConditionalActionBinding.swift
- FlintCore/Conditional Features/ConditionalFeature.swift
- FlintCore/Core/ActionDispatcher.swift
- FlintCore/Core/ActionSession.swift
- FlintCore/Core/ActionStackEntry.swift
- FlintCore/Core/ActionsBuilder.swift
- FlintCore/Core/Flint.swift
- FlintCore/Core/TopicPath+Extensions.swift
- FlintCore/Features/Feature.swift
- FlintCore/Routes/LinkCreator.swift
- FlintCore/Routes/URLMappingsBuilder.swift
- FlintCore/Siri Intents and Shortcuts/SiriShortcutDonatingActionDispatchObserver.swift
- FlintCore/Siri Intents and Shortcuts/StaticActionBinding+Shortcut+Extensions.swift
- FlintCore/Timeline/Timeline.swift
- FlintCoreTests/IntentBindingTests.swift
Remove the references to Feature and Action types in the binding. All functions at access a binding are by their nature generic over these types, so the type info is always available.
This actually makes the code a bit cleaner.
> Remove storage of feature + action types in properties in bindings

- FlintCore/Actions/ActionMetadata.swift
- FlintCore/Routes/URLMapping.swift
- FlintUISandbox/FakeFeatures.swift
It now looks like this, more human-readable.
> Fix description of URL routes in debug Feature Browser UI

- FlintCore.xcodeproj/project.pbxproj
- FlintCore/Constraints/FeatureConstraintsBuilder+Extensions.swift
- FlintCore/Constraints/Preconditions/PurchasePreconditionEvaluator.swift
- FlintCore/Core/Flint.swift
- FlintCore/Purchases/AutoRenewingSubscriptionProduct.swift
- FlintCore/Purchases/ConsumableProduct.swift
- FlintCore/Purchases/DebugPurchaseTracker.swift
- FlintCore/Purchases/NoQuantityProduct.swift
- FlintCore/Purchases/NonConsumableProduct.swift
- FlintCore/Purchases/NonRenewingSubscriptionProduct.swift
- FlintCore/Purchases/Product.swift
- FlintCore/Purchases/PurchaseRequirement.swift
- FlintCore/Purchases/PurchaseTracker.swift
- FlintCore/Purchases/StoreKit-Specific/StoreKitPurchaseTracker.swift
- FlintCore/Purchases/SubscriptionProduct.swift
- FlintCoreTests/DefaultAvailabilityCheckerTests.swift
- FlintCoreTests/Mocks and Helpers/MockPurchaseValidator.swift
- FlintUI/iOS/View Controllers/PurchaseBrowserViewController.swift
- FlintUISandbox/FakeFeatures.swift
We need to add support at the API level for at least describing and basic verification of consumable purchases, non-renewing subscriptions and auto-renewing subscription.
> Purchase API improvements

- FlintCore.xcodeproj/project.pbxproj
- FlintCore/Actions/Action+Extensions.swift
- FlintCore/Conditional Features/ConditionalFeature.swift
- FlintCore/Conditional Features/ConditionalFeatureDefinition.swift
- FlintCore/Constraints/ConstraintsEvaluator.swift
- FlintCore/Constraints/DefaultFeatureConstraintsEvaluator.swift
- FlintCore/Constraints/FeatureConstraintsBuilder+Extensions.swift
- FlintCore/Constraints/Permissions/SystemPermissionChecker.swift
- FlintCore/Constraints/Preconditions/FeaturePreconditionEvaluator.swift
- FlintCore/Core/ActionStackTracker.swift
- FlintCore/Core/Flint.swift
- FlintCore/Features/Feature.swift
- FlintCore/Features/FeatureDefinition.swift
- FlintCore/Features/FeatureGroup.swift
- FlintCore/Purchases/StoreKit-Specific/StoreKitPurchaseTracker.swift
- FlintCoreTests/Test Features/DummyFeature.swift
- FlintUI/iOS/View Controllers/PurchaseBrowserViewController.swift
- FlintUISandbox/AppDelegate.swift
New pattern for passing optional config closure to Flint setup calls, allowing configuration of custom dependencies while still guaranteeing that logging has been setup in quickSetup, and moving default dependency handling for purchases and user toggles to `quickSetup` only. Using explicit `setup` means you have not purchase tracker or user toggles unless you configure these yourself.
Open question: should availability checker and constraints evaluator be part of this? It makes for an easier hack/circumvention point but is useful for testing.
Fixes #240
> Update dependency mechanism

- FlintCore/Actions/Action.swift
- FlintCore/Activities/PerformIncomingActivityAction.swift
- FlintCore/Siri Intents and Shortcuts/UIKit-Specific/StaticActionBinding+Shortcut+Extensions.swift
- FlintCore/Siri Intents and Shortcuts/UIKit-Specific/VerifiedActionBinding+Shortcut+Extensions.swift
- FlintCore/Siri Intents and Shortcuts/UIKit-Specific/VoiceShortcuts.swift
Numerous new API tweaks fell out of updating Hobson app to support shortcuts.
* A new API `shortcut(input:)` to return `INShortcut` to support registering suggested shortcuts #
* Extra overloads of `addVoiceShortcut` to support intent-based shortcuts (previously just activity used because of generic type issues) #253 
* New `editVoiceShortcut` API to support editing/removing previously registered voice shortcut
* New completion argument to `addVoiceShortcut` & `editVoiceShortcut` functions so app UI can detected changes and cancellation
* Argument name changes away from `xxx(for:)` to `xxx(input:)` to increase consistency
* Automatically use `suggestedVoicePhrase` for intent shortcuts if no explicit shortcut set on the intent. #252
> Updates to shortcut/intent APIs

- FlintCore.xcodeproj/project.pbxproj
- FlintCore/Activities/ActionActivityMappings.swift
- FlintCore/Analytics/AnalyticsFeature.swift
- FlintCore/Analytics/AnalyticsReporting.swift
- FlintCore/Core/FlintFeatures.swift
- FlintCore/Logging/DefaultContextSpecificLogger.swift
- FlintUISandbox/FakeFeatures.swift
Turns out Activities was not resolving the correct `prepare` function since we added the throws requirement but it wasn’t added to the sandbox’s fake action.
Fixes #9
> Add Analytics feature and fix bug in UISandbox use of Activities

- FlintCore.xcodeproj/project.pbxproj
- FlintCore/Analytics/AnalyticsFeature.swift
- FlintCore/Core/ActionSession.swift
- FlintCore/Core/ActionStacksFeature.swift
- FlintCore/Core/FlintFeatures.swift
- FlintCore/Utils/CompletionRequirement.swift
- FlintCore/Utils/ProxyCompletionRequirement.swift
Fixes #8 
Had to bend the rules a bit here. We don't want to use Action(s) inside ActionStacksFeature because this is somewhat recursive and even without that the overheads would double for each action perform. So here we just check isAvailable.
> Make ActionStacks an optional feature. Off by default

- FlintCore/Focus/FocusFeature.swift
- FlintUI/Features/FocusLogDataAccessFeature.swift
- FlintUI/iOS/View Controllers/TimelineViewController.swift
- FlintUISandbox/AppDelegate.swift
For now we'll combine prod + dev logs when collecting focus logs. The issue is we want to be able to have a live viewer that sees the updates coming in, with paging to go into past entries, and with two separate histories this is too ugly to other with given that we issue async notifications to the UI if there are live updates.
If you're focusing you probably want it all. One caveat: we can't currently tell which entries are from prod or from dev but we can tackle that after 1.0. We'll probably add an entry source to LogEvent so every log event is fully self describing.
Fixes #15
> Combine dev + prod logs for focus logging purposes. 

- FlintCore/Actions/UIKit-Specific/DismissingUIAction.swift
- FlintCore/Focus/FocusFeature.swift
- FlintCore/Siri Intents and Shortcuts/IntentAction.swift
- FlintCore/Siri Intents and Shortcuts/UIKit-Specific/StaticActionBinding+Shortcut+Extensions.swift
- FlintCore/Siri Intents and Shortcuts/UIKit-Specific/VerifiedActionBinding+Shortcut+Extensions.swift
> Fix typealias warnings by holding the generics right.

- FlintCore.xcodeproj/xcshareddata/xcschemes/FlintCore-iOS.xcscheme
- FlintCore/Siri Intents and Shortcuts/IntentShortcutDonationFeature.swift
- FlintCore/Siri Intents and Shortcuts/Intents-Specific/DonateShortcutIntentAction.swift
- FlintCore/Siri Intents and Shortcuts/Intents-Specific/SiriShortcutDonatingActionDispatchObserver.swift
Hopefully this will fix:
```
/Carthage/Checkouts/Flint/FlintCore/Siri Intents and Shortcuts/IntentShortcutDonationFeature.swift:36:40: error: use of unresolved identifier 'DonateShortcutIntentAction'
static var donateShortcut = action(DonateShortcutIntentAction.self)
^~~~~~~~~~~~~~~~~~~~~~~~~~
/Carthage/Checkouts/Flint/FlintCore/Siri Intents and Shortcuts/IntentShortcutDonationFeature.swift:46:61: error: use of unresolved identifier 'SiriShortcutDonatingActionDispatchObserver'
ActionSession.main.dispatcher.add(observer: SiriShortcutDonatingActionDispatchObserver())
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> More compile issues with UIKitForMac builds

- FlintCore/Siri Intents and Shortcuts/IntentAction.swift
Without this, any actions that conform to IntentAction fail to compile as the compiler doesn't see the `PresenterType` which should be inferred by the compiler from the `where` clause in `IntentAction` as per Slava's comments in WWDC labs.
> Reinstate the PresenterType declaration, it is still required it seems
