FlintCore/Conditional Features/UserFeatureToggles.swift, FlintCore/Core/Flint.swift
Also removed the `set` function on `UserFeatureToggles` as it should only be on the implementation.
=> Make user toggles + purchase tracker public

FlintCore/Conditional Features/ConditionalFeatureDefinition.swift
=> Add the missing protocol property which prevented polymorphism.

FlintCore/Activities/ActivitiesFeature.swift, FlintCore/Activities/PublishCurrentActionActivityAction.swift, FlintCore/Core/Flint.swift, FlintCore/Features/FeatureDefinition.swift, FlintUI/Features/TimelineBrowserFeature.swift
Fixes #41 - we’re just logging them out for now
=> Add postPrepare, and NSUserActivity plist sanity checking

FlintCore/Activities/ActivityEligibility.swift, FlintCore/Activities/PublishCurrentActionActivityAction.swift, FlintUI.xcodeproj/project.pbxproj
This prediction support will not work well yet because we're not using userInfoKeys. This will come in a refactor of activities handling soon.
=> Adds initial checking for Xcode 10 and isEligibleForPrediction support

FlintCore/Core/Flint.swift, FlintCore/Routes/LinkCreator.swift, FlintCore/Routes/URLMapping.swift, FlintUISandbox/Assets.xcassets/AppIcon.appiconset/Contents.json
=> Create link creator even if scheme or domain is missing

FlintCore/Core/Flint.swift
Explain the rationale behind "register"
=> Improved docs.

FlintCore/Actions/ActionOutcome.swift, FlintCore/Actions/ActionPerformOutcome.swift, FlintCore/Activities/ActionActivityMappings.swift, FlintCore/Activities/ActivityActionDispatchObserver.swift, FlintCore/Activities/HandleActivityAction.swift, FlintCore/Activities/PerformIncomingActivityAction.swift, FlintCore/Activities/PublishCurrentActionActivityAction.swift, FlintCore/Core/ActionSession.swift, FlintCore/Core/Flint.swift, FlintCore/Focus/FocusFeature.swift, FlintCore/Routes/PerformIncomingURLAction.swift, FlintCoreTests/ActionDispatchTests.swift, FlintCoreTests/ActionSessionTests.swift, FlintCoreTests/Test Features/DummyFeature.swift, FlintUI/Features/ActionStackBrowserFeature.swift, FlintUI/Features/FeatureBrowserFeature.swift, FlintUI/Features/FocusLogDataAccessFeature.swift, FlintUI/Features/LogBrowserFeature.swift, FlintUI/Features/TimelineBrowserFeature.swift, FlintUI/Features/TimelineDataAccessFeature.swift, FlintUISandbox/FakeFeatures.swift
This tackles #141 
Naming things is hard.
=> Refactor the cases of ActionPerformOutcome

FlintCore.xcodeproj/project.pbxproj
=> Turn on extension safe APIs option

FlintCore/Conditional Features/ConditionalFeature.swift, FlintCore/Constraints/DefaultFeatureConstraintsEvaluator.swift, FlintCore/Constraints/Permissions/FeaturePermissionRequirements.swift, FlintCore/Core/ActionSession.swift, FlintCore/Routes/URLMappingsBuilder.swift
=> Add hints for dev when conditional feature request() fails

FlintCore/Utils/ErrorFunctions.swift
=> Add line numbers and file to “asserts”

FlintCore/Activities/ActivityBuilder.swift, FlintCore/Activities/ActivityEligibility.swift
Well, there was nothing to do in the end but a little cleanup.
=> Doc tweaks. Fixes #198

FlintCore/Activities/ActivityBuilder.swift
=> Add support for persistentIdentifier to the activity builder. #195

FlintCore/Core/Flint.swift, FlintCore/Logging/DefaultLoggerFactory.swift, FlintCore/Logging/Logging.swift, FlintCore/Logging/PrintLoggerOutput.swift, FlintCore/Logging/VerboseLogEventFormatter.swift, FlintCoreTests/DefaultAvailabilityCheckerTests.swift, FlintUISandbox/AppDelegate.swift
Use the new formatter strategy, clean up some naming
=> Print logger refactor

FlintCore/Features/FeatureMetadata.swift, FlintCore/Routes/ActionURLMappings.swift, FlintCore/Routes/PerformIncomingURLAction.swift, FlintCore/Routes/RegexURLPattern.swift, FlintCore/Routes/URLMapping.swift, FlintCore/Routes/URLMappings.swift, FlintCore/Routes/URLMappingsBuilder.swift, FlintCore/Routes/URLPattern.swift, FlintCoreTests/URLMappingRouterTests.swift, FlintCoreTests/URLMappingTests.swift
This addresses numerous problems found by @kokhong20 -
* URLs that don't begin with / cannot be mapped, always mapped as /xxx (#228)
* Multiple URLs per feature cannot be mapped. (#227)
* Completion status of actions performed through URL mappings is not reported. (#225)
=> URL mapping fixes

FlintCore/Logging/File Logging/FileLoggerOutput.swift, FlintCore/Logging/VerboseLogEventFormatter.swift, FlintCore/Siri Intents and Shortcuts/DonateShortcutIntentAction.swift
=> Stop double-LFs on print logger

FlintCore.podspec, FlintCore.xcodeproj/project.pbxproj, FlintUI.podspec, FlintUI.xcodeproj/project.pbxproj
This fixes #146 - at least in theory.
=> Add a first attempt at podspecs for FlintCore and FlintUI

FlintCore/Purchases/StoreKit-Specific/StoreKitPurchaseTracker.swift
=> Check and store date of purchase status

FlintCore.xcodeproj/project.pbxproj, FlintCore/Activities/ActivityBuilder.swift, FlintCore/Siri Intents and Shortcuts/UIKit-Specific/IntentAction+Internal+Extensions.swift, FlintCore/Siri Intents and Shortcuts/UIKit-Specific/StaticActionBinding+Shortcut+Extensions.swift, FlintCore/Siri Intents and Shortcuts/UIKit-Specific/VerifiedActionBinding+Shortcut+Extensions.swift, FlintCore/Siri Intents and Shortcuts/UIKit-Specific/VoiceShortcuts.swift
=> Add safety warnings for suggestedVoicePhrase being nil

FlintCore/Actions/NoInput.swift, FlintCore/Actions/StaticActionBinding.swift, FlintCore/Conditional Features/VerifiedActionBinding.swift, FlintCore/Core/ActionSession.swift, FlintCoreTests/ActionDispatchTests.swift, FlintCoreTests/Test Features/DummyFeature.swift
=> Rename .none to .noInput

FlintCore/Actions/ActionRequest.swift, FlintCore/Constraints/DefaultFeatureConstraintsBuilder.swift, FlintCore/Purchases/Product.swift, FlintCore/Purchases/PurchaseRequirement.swift, FlintCoreTests/Test Features/DummyFeature.swift, FlintUISandbox/AppDelegate.swift
=> Add referencedProducts property and fix TSAN bug

FlintCore.xcodeproj/project.pbxproj, FlintCore/Core/ActionStack.swift, FlintCore/Core/ActionStackTracker.swift, FlintCore/Focus/FocusLogging.swift, FlintCore/Timeline/Timeline.swift, FlintCore/Utils/FIFOArray.swift, FlintCore/Utils/FIFOArrayDataSource.swift
Turns out the old LIFOArrayQueue was incorrectly named. FIFO!
=> Adapt ActionStack to use FIFO array, rename LIFOArrayQueue

FlintCore.xcodeproj/project.pbxproj, FlintCore/Activities/ActionActivityMappings.swift, FlintCore/Activities/ActivityBuilder.swift, FlintUISandbox/FakeFeatures.swift
=> Rework activity builder to lazily create + allow custom activityTypes

FlintCore/Core/Flint.swift, FlintCore/Core/FlintInternal.swift, FlintCoreTests/FlintTests.swift
=> Require setup before register() is called

FlintCore/Logging/FocusContextualLoggerTarget.swift, FlintUISandbox/AppDelegate.swift
=> Let errors through the focus log filter always

FlintCore.xcodeproj/project.pbxproj, FlintCore/Activities/ActivitiesFeature.swift, FlintCore/Activities/PublishCurrentActionActivityAction.swift, FlintCore/Activities/ResignCurrentActivityAction.swift
Fixes #11 
We won't do anything smart for now. You can perform the resign via this action.
=> Add resignCurrentActivity action

FlintCore.xcodeproj/project.pbxproj, FlintCore/Constraints/Permissions/AVCaptureDevicePermissionAdapter.swift, FlintCore/Constraints/Permissions/DefaultPermissionChecker.swift, FlintCore/Constraints/Permissions/MicrophonePermissionAdapter.swift, FlintCore/Constraints/Permissions/SystemPermissionConstraint.swift, FlintCore/Core/Flint.swift, FlintCore/Core/FlintAppInfo.swift
=> Add camera permission on macOS 10.14+, mic perm on iOS+macOS 10.14+

FlintCore/Core/Flint.swift, FlintCore/Features/FeatureDefinition.swift, FlintCore/Logging/DefaultLoggerFactory.swift, FlintCore/Logging/FocusContextualLoggerTarget.swift, FlintCore/Logging/LoggerLevel.swift, FlintCore/Logging/Logging.swift, FlintCore/Logging/OSLogOutput.swift, FlintCoreTests/ActionSessionTests.swift, FlintCoreTests/DebugReportingTests.swift, FlintCoreTests/DefaultAvailabilityCheckerTests.swift, FlintUISandbox/AppDelegate.swift
There was a dreaded Optional.none problem
Fixes  #132
=> Fix suppression of internal logging

FlintCore/Actions/ActionOutcome.swift, FlintCore/Core/ActionDispatcher.swift, FlintCore/Core/ActionSession.swift, FlintCoreTests/ActionSessionTests.swift
Various queue requirements and sync vs. async completion
Fixes #44
=> Unit tests for performing actions via an ActionSession

FlintCore.xcodeproj/project.pbxproj, FlintCoreTests/ActionDispatchTests.swift, FlintCoreTests/ActionPerformTests.swift, FlintCoreTests/ActionSessionTests.swift, FlintCoreTests/Mocks and Helpers/MockPresenter.swift, FlintCoreTests/Mocks and Helpers/Sessions.swift
=> Add unit tests for action perform APIs

FlintCore.xcodeproj/xcshareddata/xcschemes/FlintCore-iOS.xcscheme, FlintCoreTests/URLMappingRouterTests.swift
=> Add unit tests for routing associated domain deep links

FlintCore/Actions/Action.swift, FlintCore/Actions/UIKit-Specific/DismissingUIAction.swift, FlintCore/Siri Intents and Shortcuts/IntentAction.swift, FlintCore/Siri Intents and Shortcuts/UIKit-Specific/StaticActionBinding+Shortcut+Extensions.swift, FlintCore/Siri Intents and Shortcuts/UIKit-Specific/VerifiedActionBinding+Shortcut+Extensions.swift
=> Fix the typealias issues properly
